In [359]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("survey_results_public.csv")

In [360]:
df.head()

Respondent                                         MainBranch Hobbyist  \
0           1                     I am a developer by profession      Yes   
1           2                     I am a developer by profession       No   
2           3                        I code primarily as a hobby      Yes   
3           4                     I am a developer by profession      Yes   
4           5  I used to be a developer by profession, but no...      Yes   

    Age Age1stCode CompFreq  CompTotal  ConvertedComp             Country  \
0   NaN         13  Monthly        NaN            NaN             Germany   
1   NaN         19      NaN        NaN            NaN      United Kingdom   
2   NaN         15      NaN        NaN            NaN  Russian Federation   
3  25.0         18      NaN        NaN            NaN             Albania   
4  31.0         16      NaN        NaN            NaN       United States   

     CurrencyDesc  ...                  SurveyEase           SurveyLength  \
0   European Euro  ...  Neither easy nor difficult  Appropriate in length   
1  Pound sterling  ...                         NaN                    NaN   
2             NaN  ...  Neither easy nor difficult  Appropriate in length   
3    Albanian lek  ...                         NaN                    NaN   
4             NaN  ...                        Easy              Too short   

  Trans                                     UndergradMajor  \
0    No  Computer science, computer engineering, or sof...   
1   NaN  Computer science, computer engineering, or sof...   
2   NaN                                                NaN   
3    No  Computer science, computer engineering, or sof...   
4    No  Computer science, computer engineering, or sof...   

  WebframeDesireNextYear    WebframeWorkedWith  \
0           ASP.NET Core  ASP.NET;ASP.NET Core   
1                    NaN                   NaN   
2                    NaN                   NaN   
3                    NaN                   NaN   
4   Django;Ruby on Rails         Ruby on Rails   

                              WelcomeChange WorkWeekHrs YearsCode YearsCodePro  
0   Just as welcome now as I felt last year        50.0        36           27  
1  Somewhat more welcome now than last year         NaN         7            4  
2  Somewhat more welcome now than last year         NaN         4          NaN  
3  Somewhat less welcome now than last year        40.0         7            4  
4   Just as welcome now as I felt last year         NaN        15            8  

[5 rows x 61 columns]

In [361]:
df['DB'] = df['DatabaseWorkedWith']
df['Language'] = df['LanguageWorkedWith']
df['DevType'] = df['DevType']
df['Technology'] = df['MiscTechWorkedWith']

In [362]:
df.head()

Respondent                                         MainBranch Hobbyist  \
0           1                     I am a developer by profession      Yes   
1           2                     I am a developer by profession       No   
2           3                        I code primarily as a hobby      Yes   
3           4                     I am a developer by profession      Yes   
4           5  I used to be a developer by profession, but no...      Yes   

    Age Age1stCode CompFreq  CompTotal  ConvertedComp             Country  \
0   NaN         13  Monthly        NaN            NaN             Germany   
1   NaN         19      NaN        NaN            NaN      United Kingdom   
2   NaN         15      NaN        NaN            NaN  Russian Federation   
3  25.0         18      NaN        NaN            NaN             Albania   
4  31.0         16      NaN        NaN            NaN       United States   

     CurrencyDesc  ...                                     UndergradMajor  \
0   European Euro  ...  Computer science, computer engineering, or sof...   
1  Pound sterling  ...  Computer science, computer engineering, or sof...   
2             NaN  ...                                                NaN   
3    Albanian lek  ...  Computer science, computer engineering, or sof...   
4             NaN  ...  Computer science, computer engineering, or sof...   

  WebframeDesireNextYear    WebframeWorkedWith  \
0           ASP.NET Core  ASP.NET;ASP.NET Core   
1                    NaN                   NaN   
2                    NaN                   NaN   
3                    NaN                   NaN   
4   Django;Ruby on Rails         Ruby on Rails   

                              WelcomeChange WorkWeekHrs YearsCode  \
0   Just as welcome now as I felt last year        50.0        36   
1  Somewhat more welcome now than last year         NaN         7   
2  Somewhat more welcome now than last year         NaN         4   
3  Somewhat less welcome now than last year        40.0         7   
4   Just as welcome now as I felt last year         NaN        15   

  YearsCodePro                                         DB  \
0           27  Elasticsearch;Microsoft SQL Server;Oracle   
1            4                                        NaN   
2          NaN                                        NaN   
3            4                                        NaN   
4            8              MySQL;PostgreSQL;Redis;SQLite   

                   Language      Technology  
0    C#;HTML/CSS;JavaScript  .NET;.NET Core  
1          JavaScript;Swift    React Native  
2  Objective-C;Python;Swift             NaN  
3                       NaN             NaN  
4         HTML/CSS;Ruby;SQL         Ansible  

[5 rows x 64 columns]

In [363]:
df = df[["Country", "EdLevel", "YearsCodePro", "Employment", "DB", "Language", "DevType", "Technology"]]
df.head()

Country                                          EdLevel  \
0             Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
1      United Kingdom     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2  Russian Federation                                              NaN   
3             Albania  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
4       United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

  YearsCodePro                                         Employment  \
0           27  Independent contractor, freelancer, or self-em...   
1            4                                 Employed full-time   
2          NaN                                                NaN   
3            4                                                NaN   
4            8                                 Employed full-time   

                                          DB                  Language  \
0  Elasticsearch;Microsoft SQL Server;Oracle    C#;HTML/CSS;JavaScript   
1                                        NaN          JavaScript;Swift   
2                                        NaN  Objective-C;Python;Swift   
3                                        NaN                       NaN   
4              MySQL;PostgreSQL;Redis;SQLite         HTML/CSS;Ruby;SQL   

                                             DevType      Technology  
0  Developer, desktop or enterprise applications;...  .NET;.NET Core  
1            Developer, full-stack;Developer, mobile    React Native  
2                                                NaN             NaN  
3                                                NaN             NaN  
4                                                NaN         Ansible

In [364]:
df = df[df["DB"].notnull()]
df = df[df["Language"].notnull()]
df = df[df["DevType"].notnull()]
df = df[df["Technology"].notnull()]
df.head()

Country                                          EdLevel  \
0          Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
7    United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
9   United Kingdom  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
10  United Kingdom     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
13   United States              Associate degree (A.A., A.S., etc.)   

   YearsCodePro                                         Employment  \
0            27  Independent contractor, freelancer, or self-em...   
7            13                                 Employed full-time   
9             4                                 Employed full-time   
10            2                                 Employed full-time   
13            1                                 Employed full-time   

                                           DB  \
0   Elasticsearch;Microsoft SQL Server;Oracle   
7                         MariaDB;MySQL;Redis   
9                        Microsoft SQL Server   
10         Firebase;MongoDB;PostgreSQL;SQLite   
13              Firebase;Microsoft SQL Server   

                               Language  \
0                C#;HTML/CSS;JavaScript   
7                            Python;SQL   
9   HTML/CSS;Java;JavaScript;Python;SQL   
10                  C#;JavaScript;Swift   
13   HTML/CSS;JavaScript;SQL;TypeScript   

                                              DevType      Technology  
0   Developer, desktop or enterprise applications;...  .NET;.NET Core  
7   Developer, back-end;Developer, desktop or ente...         Ansible  
9   Database administrator;Developer, full-stack;D...          Pandas  
10  Developer, back-end;Developer, desktop or ente...         Node.js  
13  Developer, desktop or enterprise applications;...         Node.js

In [365]:
df = df[df["Employment"].notnull()]
df.head()

Country                                          EdLevel  \
0          Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
7    United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
9   United Kingdom  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
10  United Kingdom     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
13   United States              Associate degree (A.A., A.S., etc.)   

   YearsCodePro                                         Employment  \
0            27  Independent contractor, freelancer, or self-em...   
7            13                                 Employed full-time   
9             4                                 Employed full-time   
10            2                                 Employed full-time   
13            1                                 Employed full-time   

                                           DB  \
0   Elasticsearch;Microsoft SQL Server;Oracle   
7                         MariaDB;MySQL;Redis   
9                        Microsoft SQL Server   
10         Firebase;MongoDB;PostgreSQL;SQLite   
13              Firebase;Microsoft SQL Server   

                               Language  \
0                C#;HTML/CSS;JavaScript   
7                            Python;SQL   
9   HTML/CSS;Java;JavaScript;Python;SQL   
10                  C#;JavaScript;Swift   
13   HTML/CSS;JavaScript;SQL;TypeScript   

                                              DevType      Technology  
0   Developer, desktop or enterprise applications;...  .NET;.NET Core  
7   Developer, back-end;Developer, desktop or ente...         Ansible  
9   Database administrator;Developer, full-stack;D...          Pandas  
10  Developer, back-end;Developer, desktop or ente...         Node.js  
13  Developer, desktop or enterprise applications;...         Node.js

In [366]:
df.head()

Country                                          EdLevel  \
0          Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
7    United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
9   United Kingdom  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
10  United Kingdom     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
13   United States              Associate degree (A.A., A.S., etc.)   

   YearsCodePro                                         Employment  \
0            27  Independent contractor, freelancer, or self-em...   
7            13                                 Employed full-time   
9             4                                 Employed full-time   
10            2                                 Employed full-time   
13            1                                 Employed full-time   

                                           DB  \
0   Elasticsearch;Microsoft SQL Server;Oracle   
7                         MariaDB;MySQL;Redis   
9                        Microsoft SQL Server   
10         Firebase;MongoDB;PostgreSQL;SQLite   
13              Firebase;Microsoft SQL Server   

                               Language  \
0                C#;HTML/CSS;JavaScript   
7                            Python;SQL   
9   HTML/CSS;Java;JavaScript;Python;SQL   
10                  C#;JavaScript;Swift   
13   HTML/CSS;JavaScript;SQL;TypeScript   

                                              DevType      Technology  
0   Developer, desktop or enterprise applications;...  .NET;.NET Core  
7   Developer, back-end;Developer, desktop or ente...         Ansible  
9   Database administrator;Developer, full-stack;D...          Pandas  
10  Developer, back-end;Developer, desktop or ente...         Node.js  
13  Developer, desktop or enterprise applications;...         Node.js

In [367]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30868 entries, 0 to 64447
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Country       30868 non-null  object
 1   EdLevel       30308 non-null  object
 2   YearsCodePro  28669 non-null  object
 3   Employment    30868 non-null  object
 4   DB            30868 non-null  object
 5   Language      30868 non-null  object
 6   DevType       30868 non-null  object
 7   Technology    30868 non-null  object
dtypes: object(8)
memory usage: 2.1+ MB


In [368]:
df = df.dropna()
df.isnull().sum()

Country         0
EdLevel         0
YearsCodePro    0
Employment      0
DB              0
Language        0
DevType         0
Technology      0
dtype: int64

In [369]:
df['Country'].value_counts()

Country
United States     6412
India             2702
United Kingdom    1974
Germany           1706
Canada            1039
                  ... 
Djibouti             1
Bahamas              1
Sierra Leone         1
Guinea               1
Mozambique           1
Name: count, Length: 165, dtype: int64

In [370]:
def shorten_categories(categories, cutoff):
    categorical_map = {}
    for i in range(len(categories)):
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = 'other'
    return categorical_map

In [371]:
country_map = shorten_categories(df.Country.value_counts(), 400)
df['Country'] = df['Country'].map(country_map)
df.Country.value_counts()

Country
other                 8831
United States         6412
India                 2702
United Kingdom        1974
Germany               1706
Canada                1039
Brazil                 901
France                 825
Netherlands            641
Australia              631
Poland                 573
Spain                  548
Italy                  543
Russian Federation     456
Sweden                 421
Name: count, dtype: int64

In [372]:
df.DB.value_counts()

DB
Microsoft SQL Server                                                                   2442
MySQL                                                                                  1089
PostgreSQL                                                                              908
Microsoft SQL Server;MySQL                                                              656
MongoDB                                                                                 553
                                                                                       ... 
Couchbase;DynamoDB;MariaDB;MySQL;Oracle;PostgreSQL;Redis;SQLite                           1
DynamoDB;Elasticsearch;Firebase;Microsoft SQL Server;MySQL;Oracle;PostgreSQL;SQLite       1
Elasticsearch;IBM DB2;Microsoft SQL Server;MongoDB                                        1
Cassandra;DynamoDB;Elasticsearch                                                          1
Cassandra;Couchbase;DynamoDB;Firebase;IBM DB2                                

In [373]:
db_map = shorten_categories(df.DB.value_counts(), 300)
df['DB'] = df['DB'].map(db_map)
df.DB.value_counts()

DB
other                                19538
Microsoft SQL Server                  2442
MySQL                                 1089
PostgreSQL                             908
Microsoft SQL Server;MySQL             656
MongoDB                                553
Microsoft SQL Server;SQLite            462
MySQL;PostgreSQL                       423
SQLite                                 419
MongoDB;MySQL                          382
MySQL;SQLite                           375
Microsoft SQL Server;PostgreSQL        330
Microsoft SQL Server;MySQL;SQLite      319
MariaDB;MySQL                          307
Name: count, dtype: int64

In [374]:
# Identify values with counts less than 300
value_counts = df['Language'].value_counts()
mask = df['Language'].isin(value_counts.index[value_counts < 300])

# Replace values with counts less than 300 with 'Others'
df.loc[mask, 'Language'] = 'Others'
df.Language.value_counts()

Language
Others                                                         25793
C#;HTML/CSS;JavaScript;SQL                                       738
C#;HTML/CSS;JavaScript;SQL;TypeScript                            671
HTML/CSS;JavaScript;TypeScript                                   348
HTML/CSS;JavaScript;PHP;SQL                                      345
Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;SQL;TypeScript      308
Name: count, dtype: int64

In [375]:
# Identify values with counts less than 300
value_counts = df['DevType'].value_counts()
mask = df['DevType'].isin(value_counts.index[value_counts < 300])

# Replace values with counts less than 300 with 'Others'
df.loc[mask, 'DevType'] = 'Others'
df.DevType.value_counts()

DevType
Others                                                                                                          18609
Developer, full-stack                                                                                            2779
Developer, back-end;Developer, front-end;Developer, full-stack                                                   1473
Developer, back-end                                                                                              1335
Developer, back-end;Developer, full-stack                                                                         874
Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack      595
Developer, front-end;Developer, full-stack                                                                        509
Developer, front-end                                                                                              494
Developer, back-end;Developer, front-end;Develop

In [376]:
# Identify values with counts less than 300
value_counts = df['Technology'].value_counts()
mask = df['Technology'].isin(value_counts.index[value_counts < 300])

# Replace values with counts less than 300 with 'Others'
df.loc[mask, 'Technology'] = 'Others'
df.Technology.value_counts()

Technology
Others                    12007
Node.js                    4927
.NET;.NET Core             2564
.NET                       1774
.NET;.NET Core;Node.js     1327
Node.js;React Native        900
Pandas                      774
Ansible                     552
.NET;Node.js                540
.NET Core                   436
Cordova;Node.js             376
React Native                374
.NET;.NET Core;Xamarin      371
Flutter                     337
.NET Core;Node.js           329
Ansible;Node.js             308
Node.js;Pandas              307
Name: count, dtype: int64

In [377]:
df["YearsCodePro"].unique()

array(['27', '13', '4', '2', '1', '3', '17', '14', '12', '20', '10', '29',
       '28', '23', '15', '11', '7', '25', '9', '8', 'Less than 1 year',
       '5', '21', '16', '6', '35', '18', '32', '19', '30', '38', '24',
       '22', '26', '40', '31', 'More than 50 years', '33', '34', '39',
       '37', '41', '45', '36', '50', '42', '43', '44', '46', '49', '47'],
      dtype=object)

In [378]:
def clean_experience(x):
    if x == "More than 50 years":
        return 50
    if x == "Less than 1 year":
        return 0.5
    return float(x)
df['YearsCodePro'] = df['YearsCodePro'].apply(clean_experience)

In [379]:
df["EdLevel"].unique()

array(['Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Associate degree (A.A., A.S., etc.)',
       'Some college/university study without earning a degree',
       'Other doctoral degree (Ph.D., Ed.D., etc.)',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Professional degree (JD, MD, etc.)', 'Primary/elementary school',
       'I never completed any formal education'], dtype=object)

In [380]:
def clean_education(x):
    if pd.isnull(x) or isinstance(x, float):
        return "Unknown"  # or any default value you prefer for missing data
    if "Bachelor’s degree" in x:
        return "Bachelor's degree"
    if "Master’s degree" in x:
        return "Master's degree"
    if "Professional degree" in x or "Other doctoral" in x:
        return "Post grad"
    return "Less than a Bachelors"

df["EdLevel"] = df["EdLevel"].apply(clean_education)


In [381]:
df["EdLevel"].unique()

array(["Master's degree", "Bachelor's degree", 'Less than a Bachelors',
       'Post grad'], dtype=object)

In [382]:
from sklearn.preprocessing import LabelEncoder
le_education = LabelEncoder()
df['EdLevel'] = le_education.fit_transform(df['EdLevel'])
df['EdLevel'].unique()

array([2, 0, 1, 3])

In [383]:
le_country = LabelEncoder()
df['Country'] = le_country.fit_transform(df['Country'])
df['Country'].unique()

array([ 4, 13, 12, 10, 14,  3,  6,  1, 11,  2,  7,  5,  8,  0,  9])

In [384]:
df['Employment'].unique()

array(['Independent contractor, freelancer, or self-employed',
       'Employed full-time', 'Employed part-time'], dtype=object)

In [385]:
def clean_employment(x):
    if "Independent contractor, freelancer, or self-employed" in x:
        return "Not employed"
    if "Employed full-time" in x:
        return "Employed full-time"
    if "Employed part-time" in x:
        return "Intern"
    return "Not employed"

df["Employment"] = df["Employment"].apply(clean_employment)

In [386]:
df['Employment'].unique()

array(['Not employed', 'Employed full-time', 'Intern'], dtype=object)

In [387]:
le_employment = LabelEncoder()
df['Employment'] = le_employment.fit_transform(df['Employment'])
df['Employment'].unique()

array([2, 0, 1])

In [388]:
df['DB'].unique()

array(['other', 'Microsoft SQL Server', 'Microsoft SQL Server;PostgreSQL',
       'SQLite', 'MongoDB', 'Microsoft SQL Server;MySQL', 'MySQL',
       'PostgreSQL', 'Microsoft SQL Server;MySQL;SQLite',
       'Microsoft SQL Server;SQLite', 'MySQL;PostgreSQL', 'MariaDB;MySQL',
       'MongoDB;MySQL', 'MySQL;SQLite'], dtype=object)

In [389]:
df['Language'].unique()

array(['Others',
       'Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;SQL;TypeScript',
       'HTML/CSS;JavaScript;TypeScript', 'C#;HTML/CSS;JavaScript;SQL',
       'C#;HTML/CSS;JavaScript;SQL;TypeScript',
       'HTML/CSS;JavaScript;PHP;SQL'], dtype=object)

In [390]:
df['DevType'].unique()

array(['Others', 'Developer, full-stack', 'Developer, front-end',
       'Developer, back-end;Developer, front-end;Developer, full-stack',
       'Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack',
       'Developer, front-end;Developer, full-stack',
       'Developer, back-end;Developer, desktop or enterprise applications;Developer, full-stack',
       'Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile',
       'Developer, back-end', 'Developer, back-end;Developer, full-stack',
       'Developer, back-end;Developer, desktop or enterprise applications',
       'Developer, mobile'], dtype=object)

In [391]:
df['Technology'].unique()

array(['.NET;.NET Core', 'Ansible', 'Pandas', 'Node.js', '.NET;Node.js',
       '.NET;.NET Core;Node.js', 'Node.js;React Native', 'Node.js;Pandas',
       'Others', 'Flutter', '.NET', 'Ansible;Node.js', '.NET Core',
       'Cordova;Node.js', 'React Native', '.NET Core;Node.js',
       '.NET;.NET Core;Xamarin'], dtype=object)

In [392]:
le_db = LabelEncoder()
df['DB'] = le_db.fit_transform(df['DB'])
df['DB'].unique()

array([13,  1,  4, 12,  6,  2,  8, 11,  3,  5,  9,  0,  7, 10])

In [393]:
le_language = LabelEncoder()
df['Language'] = le_language.fit_transform(df['Language'])
df['Language'].unique()

array([5, 0, 4, 1, 2, 3])

In [394]:
le_dev = LabelEncoder()
df['DevType'] = le_dev.fit_transform(df['DevType'])
df['DevType'].unique()

array([11,  9,  7,  4,  2,  8,  3,  5,  0,  6,  1, 10])

In [395]:
le_tech = LabelEncoder()
df['Technology'] = le_tech.fit_transform(df['Technology'])
df['Technology'].unique()

array([ 3,  7, 15, 11,  6,  4, 13, 12, 14, 10,  0,  8,  1,  9, 16,  2,  5])

In [396]:
df.head()

Country  EdLevel  YearsCodePro  Employment  DB  Language  DevType  \
0         4        2          27.0           2  13         5       11   
7        13        0          13.0           0  13         5       11   
9        12        2           4.0           0   1         5       11   
10       12        0           2.0           0  13         5       11   
13       13        1           1.0           0  13         5       11   

    Technology  
0            3  
7            7  
9           15  
10          11  
13          11

In [397]:
X = df.drop("Employment", axis=1)
Y = df["Employment"]

In [398]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28203 entries, 0 to 64446
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       28203 non-null  int32  
 1   EdLevel       28203 non-null  int32  
 2   YearsCodePro  28203 non-null  float64
 3   Employment    28203 non-null  int32  
 4   DB            28203 non-null  int32  
 5   Language      28203 non-null  int32  
 6   DevType       28203 non-null  int32  
 7   Technology    28203 non-null  int32  
dtypes: float64(1), int32(7)
memory usage: 1.2 MB


In [399]:
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state=0)
dec_tree_reg.fit(X, Y.values)

DecisionTreeRegressor(random_state=0)

In [400]:
y_pred = dec_tree_reg.predict(X)

In [401]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
error = np.sqrt(mean_squared_error(Y, y_pred))
print("{:,.02f}".format(error))

0.38


In [402]:
from sklearn.ensemble import RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)
random_forest_reg.fit(X, Y.values)

RandomForestRegressor(random_state=0)

In [403]:
y_pred = random_forest_reg.predict(X)

In [404]:
error = np.sqrt(mean_squared_error(Y, y_pred))
print("${:,.02f}".format(error))

$0.42


In [405]:
X

Country  EdLevel  YearsCodePro  DB  Language  DevType  Technology
0            4        2          27.0  13         5       11           3
7           13        0          13.0  13         5       11           7
9           12        2           4.0   1         5       11          15
10          12        0           2.0  13         5       11          11
13          13        1           1.0  13         5       11          11
...        ...      ...           ...  ..       ...      ...         ...
64416       14        0           3.0   1         5       11           0
64420       14        0           0.5  13         5        9          13
64427        1        2          14.0  13         5       11          14
64429       10        1           1.0  13         5       10          14
64446        0        1           2.0   6         5       11          14

[28203 rows x 7 columns]

In [406]:
Y

0        2
7        0
9        0
10       0
13       0
        ..
64416    1
64420    0
64427    0
64429    2
64446    2
Name: Employment, Length: 28203, dtype: int32

In [407]:
X = np.array([["United States", "Master's degree" , 15, "MongoDB", "C#;HTML/CSS;JavaScript;SQL", "Developer, full-stack", "Pandas"]])

In [408]:
X

array([['United States', "Master's degree", '15', 'MongoDB',
        'C#;HTML/CSS;JavaScript;SQL', 'Developer, full-stack', 'Pandas']],
      dtype='<U26')

In [409]:
X[:, 0] = le_country.transform(X[:,0])
X[:, 1] = le_education.transform(X[:,1])
X[:, 3] = le_db.transform(X[:,3])
X[:, 4] = le_language.transform(X[:,4])
X[:, 5] = le_dev.transform(X[:,5])
X[:, 6] = le_tech.transform(X[:,6])

X = X.astype(float)
X

array([[13.,  2., 15.,  6.,  1.,  9., 15.]])

In [410]:
y_pred = random_forest_reg.predict(X)
y_pred

c:\Users\muham\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([0.41])

In [411]:
rounded_prediction = round(y_pred[0])
inverse_mapping = {2: 'Not employed', 0: 'Employed full-time', 1: 'Intern'}
original_prediction = inverse_mapping[rounded_prediction]

print(original_prediction)

Employed full-time


In [412]:
import pickle

In [413]:
data = {"model": random_forest_reg, "le_country": le_country, "le_education": le_education, "le_db" : le_db, "le_language": le_language, "le_dev": le_dev, "le_tech": le_tech, "le_employment" : le_employment}
with open('saved_steps2.pkl', 'wb') as file:
    pickle.dump(data, file)

In [414]:
with open('saved_steps2.pkl', 'rb') as file:
    data = pickle.load(file)
regressor_loaded = data["model"]
le_country = data["le_country"]
le_education = data["le_education"]
le_db = data["le_db"]
le_language = data["le_language"]
le_dev = data["le_dev"]
le_tech = data["le_tech"]
le_employment = data["le_employment"]

In [415]:
y_pred = regressor_loaded.predict(X)
y_pred

c:\Users\muham\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([0.41])

In [416]:
df.Skills.value_counts()

AttributeError: 'DataFrame' object has no attribute 'Skills'